### Importing all necessary packages


In [36]:
#import glob
#import sys
#import audiofile
#import time
import pandas as pd
import os
import sklearn.mixture
import numpy as np

In [37]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import PCA
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.manifold import TSNE
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

In [38]:
import csv
rows = []
with open("./EVEN-ATTCK-DT-1.csv", 'r') as file:
    csvreader = csv.reader(file)
    # header = next(csvreader)
    for row in csvreader:
        rows.append(row)
# print(header)
# print(rows)

x = []
y = []

for i in rows:
    a = float(i[0])
    b = float(i[1])
    c = float(i[2])
    d = float(i[3])
    e = int(i[4])
    x.append([a,b,c,d])
    y.append(e)

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, shuffle=True, random_state=0)

# print(X_train)
# print(y_train)


### Random Forest


In [39]:
pipe1 = Pipeline([ ('std', StandardScaler()), ('Random_forest', RandomForestClassifier(n_estimators = 100))], verbose = True)
pipe1.fit(X_train, y_train)
prob_score_RF=pipe1.predict_proba(X_test)
print("\nAccuracy:",accuracy_score(y_test, pipe1.predict(X_test)))
print("\n----------------Classification Report----------------\n\n",classification_report(y_test,pipe1.predict(X_test)))


[Pipeline] ............... (step 1 of 2) Processing std, total=   0.0s
[Pipeline] ..... (step 2 of 2) Processing Random_forest, total=   1.1s

Accuracy: 0.9871309613928841

----------------Classification Report----------------

               precision    recall  f1-score   support

           0       0.99      1.00      0.99      2231
           1       0.98      0.93      0.96       411

    accuracy                           0.99      2642
   macro avg       0.99      0.97      0.98      2642
weighted avg       0.99      0.99      0.99      2642



#### Confusion Matrix for Random Forest


In [40]:
print(sklearn.metrics.confusion_matrix(y_test, pipe1.predict(X_test)))

[[2224    7]
 [  27  384]]


### Decision tree


In [41]:
pipe2 = Pipeline([ ('std', StandardScaler()), ('decision_tree', DecisionTreeClassifier())], verbose = True)
pipe2.fit(X_train, y_train)
prob_score_DT=pipe2.predict_proba(X_test)
print("\nAccuracy:",accuracy_score(y_test, pipe2.predict(X_test)))
print("\n----------------Classification Report----------------\n\n",classification_report(y_test,pipe2.predict(X_test)))

[Pipeline] ............... (step 1 of 2) Processing std, total=   0.0s
[Pipeline] ..... (step 2 of 2) Processing decision_tree, total=   0.0s

Accuracy: 0.9825889477668432

----------------Classification Report----------------

               precision    recall  f1-score   support

           0       0.99      0.99      0.99      2231
           1       0.96      0.93      0.94       411

    accuracy                           0.98      2642
   macro avg       0.97      0.96      0.97      2642
weighted avg       0.98      0.98      0.98      2642



#### Confusion Matrix for Decision Tree


In [42]:
print(sklearn.metrics.confusion_matrix(y_test, pipe2.predict(X_test)))

[[2215   16]
 [  30  381]]


### SVM (Support Vector Machine)


In [43]:
pipe4 = Pipeline([ ('std', StandardScaler()), ('SVM', SVC(kernel='linear',probability=True) )], verbose = True)
pipe4.fit(X_train, y_train)
prob_score_SVM=pipe4.predict_proba(X_test)
print("\nAccuracy:",accuracy_score(y_test, pipe4.predict(X_test)))
print("\n----------------Classification Report----------------\n\n",classification_report(y_test,pipe4.predict(X_test)))

[Pipeline] ............... (step 1 of 2) Processing std, total=   0.0s
[Pipeline] ............... (step 2 of 2) Processing SVM, total=   1.5s

Accuracy: 0.9663133989401969

----------------Classification Report----------------

               precision    recall  f1-score   support

           0       0.98      0.98      0.98      2231
           1       0.91      0.87      0.89       411

    accuracy                           0.97      2642
   macro avg       0.94      0.93      0.93      2642
weighted avg       0.97      0.97      0.97      2642



#### Confusion matrix for SVM


In [44]:
print(sklearn.metrics.confusion_matrix(y_test, pipe4.predict(X_test)))

[[2194   37]
 [  52  359]]


### Logistic regression


In [45]:
pipe5 = Pipeline([ ('std', StandardScaler()), ('Logistic_Regression', LogisticRegression(random_state = 0) )], verbose = True)
pipe5.fit(X_train, y_train)
prob_score_LR=pipe5.predict_proba(X_test)
print("\nAccuracy:",accuracy_score(y_test, pipe5.predict(X_test)))
print("\n----------------Classification Report----------------\n\n",classification_report(y_test,pipe5.predict(X_test)))

[Pipeline] ............... (step 1 of 2) Processing std, total=   0.0s
[Pipeline]  (step 2 of 2) Processing Logistic_Regression, total=   0.0s

Accuracy: 0.9651778955336866

----------------Classification Report----------------

               precision    recall  f1-score   support

           0       0.98      0.98      0.98      2231
           1       0.91      0.86      0.89       411

    accuracy                           0.97      2642
   macro avg       0.94      0.92      0.93      2642
weighted avg       0.96      0.97      0.96      2642



#### Confusion matrix for Logistic regression


In [46]:
print(sklearn.metrics.confusion_matrix(y_test, pipe5.predict(X_test)))

[[2195   36]
 [  56  355]]
