### Importing all necessary packages


In [40]:
#import glob
#import sys
#import audiofile
#import time
import pandas as pd
import os
import sklearn.mixture
import numpy as np
import pickle

In [41]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import PCA
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.manifold import TSNE
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

In [42]:
import csv
rows = []
with open("./generate_false_data.csv", 'r') as file:
    csvreader = csv.reader(file)
    # header = next(csvreader)
    for row in csvreader:
        rows.append(row)
# print(header)
# print(rows)

x = []
y = []

# print(rows)

for i in rows:
    # print(i)
    b = float(i[1])
    c = float(i[2])
    d = float(i[3])
    e = float(i[4])
    f = float(i[5])
    g = float(i[6])
    h = float(i[7])
    p = float(i[8])
    j = float(i[9])
    k = float(i[10])
    l = int(i[11])
    x.append([b,c,d,e,f,g,h,p,j,k])
    y.append(l)

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, shuffle=True, random_state=0)

# print(X_train)
# print(y_train)


### Random Forest


In [43]:
pipe1 = Pipeline([ ('std', StandardScaler()), ('Random_forest', RandomForestClassifier(n_estimators = 100))], verbose = True)
pipe1.fit(X_train, y_train)
filename = "./models/RF.sav"
pickle.dump(pipe1, open(filename, 'wb'))
prob_score_RF=pipe1.predict_proba(X_test)
print("\nAccuracy:",accuracy_score(y_test, pipe1.predict(X_test)))
print("\n----------------Classification Report----------------\n\n",classification_report(y_test,pipe1.predict(X_test)))

# load_model = pickle.load(open(filename, 'rb'))
# # print(X_test)
# result = load_model.predict([X_test[0]])
# print("printing result")
# print(result)

[Pipeline] ............... (step 1 of 2) Processing std, total=   0.0s
[Pipeline] ..... (step 2 of 2) Processing Random_forest, total=   0.1s

Accuracy: 1.0

----------------Classification Report----------------

               precision    recall  f1-score   support

           0       1.00      1.00      1.00        81
           1       1.00      1.00      1.00        95

    accuracy                           1.00       176
   macro avg       1.00      1.00      1.00       176
weighted avg       1.00      1.00      1.00       176



#### Confusion Matrix for Random Forest


In [44]:
print(sklearn.metrics.confusion_matrix(y_test, pipe1.predict(X_test)))

[[81  0]
 [ 0 95]]


### Decision tree


In [45]:
pipe2 = Pipeline([ ('std', StandardScaler()), ('decision_tree', DecisionTreeClassifier())], verbose = True)
pipe2.fit(X_train, y_train)
filename = "./models/DT.sav"
pickle.dump(pipe2, open(filename, 'wb'))
prob_score_DT=pipe2.predict_proba(X_test)
print("\nAccuracy:",accuracy_score(y_test, pipe2.predict(X_test)))
print("\n----------------Classification Report----------------\n\n",classification_report(y_test,pipe2.predict(X_test)))

[Pipeline] ............... (step 1 of 2) Processing std, total=   0.0s
[Pipeline] ..... (step 2 of 2) Processing decision_tree, total=   0.0s

Accuracy: 1.0

----------------Classification Report----------------

               precision    recall  f1-score   support

           0       1.00      1.00      1.00        81
           1       1.00      1.00      1.00        95

    accuracy                           1.00       176
   macro avg       1.00      1.00      1.00       176
weighted avg       1.00      1.00      1.00       176



#### Confusion Matrix for Decision Tree


In [46]:
print(sklearn.metrics.confusion_matrix(y_test, pipe2.predict(X_test)))

[[81  0]
 [ 0 95]]


### SVM (Support Vector Machine)


In [47]:
pipe4 = Pipeline([ ('std', StandardScaler()), ('SVM', SVC(kernel='linear',probability=True) )], verbose = True)
pipe4.fit(X_train, y_train)
filename = "./models/SVM.sav"
pickle.dump(pipe4, open(filename, 'wb'))
prob_score_SVM=pipe4.predict_proba(X_test)
print("\nAccuracy:",accuracy_score(y_test, pipe4.predict(X_test)))
print("\n----------------Classification Report----------------\n\n",classification_report(y_test,pipe4.predict(X_test)))

[Pipeline] ............... (step 1 of 2) Processing std, total=   0.0s
[Pipeline] ............... (step 2 of 2) Processing SVM, total=   0.1s

Accuracy: 0.6534090909090909

----------------Classification Report----------------

               precision    recall  f1-score   support

           0       0.57      0.99      0.72        81
           1       0.97      0.37      0.53        95

    accuracy                           0.65       176
   macro avg       0.77      0.68      0.63       176
weighted avg       0.79      0.65      0.62       176



#### Confusion matrix for SVM


In [48]:
print(sklearn.metrics.confusion_matrix(y_test, pipe4.predict(X_test)))

[[80  1]
 [60 35]]


### Logistic regression


In [49]:
pipe5 = Pipeline([ ('std', StandardScaler()), ('Logistic_Regression', LogisticRegression(random_state = 0) )], verbose = True)
pipe5.fit(X_train, y_train)
filename = "./models/LR.sav"
pickle.dump(pipe5, open(filename, 'wb'))
prob_score_LR=pipe5.predict_proba(X_test)
print("\nAccuracy:",accuracy_score(y_test, pipe5.predict(X_test)))
print("\n----------------Classification Report----------------\n\n",classification_report(y_test,pipe5.predict(X_test)))

[Pipeline] ............... (step 1 of 2) Processing std, total=   0.0s
[Pipeline]  (step 2 of 2) Processing Logistic_Regression, total=   0.0s

Accuracy: 0.5738636363636364

----------------Classification Report----------------

               precision    recall  f1-score   support

           0       0.53      0.78      0.63        81
           1       0.68      0.40      0.50        95

    accuracy                           0.57       176
   macro avg       0.60      0.59      0.57       176
weighted avg       0.61      0.57      0.56       176



#### Confusion matrix for Logistic regression


In [50]:
print(sklearn.metrics.confusion_matrix(y_test, pipe5.predict(X_test)))

[[63 18]
 [57 38]]
